version: "3"

services:
  frontend:
    image: juseungl/investi-mate:frontend
    container_name: frontend-container
    expose:
      - 3000
    networks:
      - investimate

  backend:
    # DockerHub 이미지 주소
    image: juseungl/investi-mate:backend
    container_name: backend-container
    expose:
      - 8080
    networks:
      - investimate

  nginx:
    image: juseungl/investi-mate:nginx
    container_name: nginx-container
    # 서비스 종속관계 명시
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - investimate

networks:
  investimate:
