name: CI/CD with Git Actions & Docker Hub

on:
  push:
    branches: [ "createrun" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-source code
        uses: actions/checkout@v3

      # application.yml 파일 생성
      - name: production application file setting
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
          echo ${{ secrets.APPLICATION_YML }} | base64 --decode >> ./src/main/resources/application.yml

      # .env파일 생성
      - name: Create .env file
        run: |
          echo ${{ secrets.ENV_FILE }} | base64 --decode > .env

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Spring boot application 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Spring boot application 도커 이미지 빌드 후 도커허브에 push하기
      - name: Spring boot app docker build and publish
        run:
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}:backend --platform linux/amd64 .
          
          docker push ${{ secrets.DOCKER_REPOSITORY }}:backend

      # nginx 도커 이미지 빌드 후 도커허브에 push하기
      - name: Nginx docker build and push
        run: |
          cd /Users/juseung/Documents/2024CD/InvestiMate/src/main/resources/nginx-config/
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}:nginx --platform linux/amd64 .
          
          docker push ${{ secrets.DOCKER_REPOSITORY }}:nginx

#      # nginx 설정 파일 서버로 전달하기(복사 후 붙여넣기)
#      - name: Send nginx.conf
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }} # 퍼블릭 IPv4 DNS
#          username: ubuntu
#          key: ${{ secrets.SSH_KEY }} # cat {ec2_instance_name}.pem
#          port: ${{ secrets.SSH_PORT }} # 보안 그룹 인바운드 규칙의 SSH Port Number
#          source: "./nginx.conf"
#          target: "/home/ubuntu/workspace/server/"

      # compose.yml 설정 파일 서버로 전달하기(복사 후 붙여넣기)
      - name: Send compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.SSH_KEY }} # cat {ec2_instance_name}.pem
          port: ${{ secrets.SSH_PORT }} # 보안 그룹 인바운드 규칙의 SSH Port Number
          source: "./docker-compose.yml"
          target: "/home/ubuntu/workspace/server/"

      # nginx.conf 경로 변경 후 도커 컴포즈 실행하기
      # 도커 허브에서 jar파일 및 pull후에 컴포즈 up
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.SSH_KEY }} # cat {ec2_instance_name}.pem
          port: ${{ secrets.SSH_PORT }} # 보안 그룹 인바운드 규칙의 SSH Port Number
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}:backend
            sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}:nginx
            cd workspace/server
            docker-compose down
            docker rmi $(docker images -q)
            docker-compose up -d

#        # Remote SSH로 EC2 인스턴스 접속 & 애플리케이션 실행
#      - name: Connect to WAS & Execute Application
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.SSH_HOST }} # 퍼블릭 IPv4 DNS
#          username: ubuntu
#          key: ${{ secrets.SSH_KEY }} # cat {ec2_instance_name}.pem
#          port: ${{ secrets.SSH_PORT }} # 보안 그룹 인바운드 규칙의 SSH Port Number
#          script: |
#            docker stop $(docker ps -a -q)
#            docker rm $(docker ps -a -q)
#            docker rmi $(sudo docker images -q)
#
#            docker pull juseungl/investi-mate
#            docker run -d -p 8080:8080 --name juseungl/investi-mate

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Login to ECR
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Set timestamp
#        id: vars
#        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
#
#      - name: Build & Push to ECR
#        run: |
#          docker build -t hwany-service .
#          IMAGE_TAG="${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.ap-northeast-2.amazonaws.com/yhp-capstone-repository:hwany-service-${TIMESTAMP}"
#          docker tag hwany-service $IMAGE_TAG
#          docker push $IMAGE_TAG
#        env:
#          TIMESTAMP: ${{ env.TIMESTAMP }}
